trigger:
- main  # This pipeline will only run manually or when triggered explicitly

pool:
  vmImage: 'ubuntu-latest'  # Specifies which VM image to use for the Azure Pipeline agent

steps:
- checkout: none  # This pipeline doesn't require access to your code repository

- task: SSH@0
  displayName: 'Test SSH Connection and Docker Command'
  inputs:
    sshEndpoint: 'ssh-ai-trader-agent'  # The name of your SSH service connection in Azure DevOps
    runOptions: 'inline'
    inline: |
      # Execute docker ps command to list all containers
      sudo docker ps

      # Optionally, you can add more commands here to test other functionalities
