trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitCredentials  # Make sure this matches the name of your variable group in Azure DevOps

steps:
- checkout: none

- task: SSH@0
  displayName: 'Deploy ai-trader-agent'
  inputs:
    sshEndpoint: 'ssh-ai-trader-agent'
    runOptions: 'inline'
    inline: |

      #Navigate to directory
      cd ai-trader-agent || true
      # Stop and remove any existing docker containers and networks
      sudo docker-compose down || true
      
      # Remove the existing directory, if it exists
      rm -r ai-trader-agent || true
      
      # Construct the Git repository URL with credentials
      GIT_REPO="https://$(GitUsername):$(GitPassword)@github.com/EthanFajnkuchen/ai-trader-agent.git"
      