version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Bot/Dockerfile
    ports:
      - "8002:80"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BASE_URL_API=${BASE_URL_API}

  trader_agent:
    build: 
      context: .
      dockerfile: TraderAgent/Dockerfile
    ports:
      - "8000:81"
    environment:
      - BASE_URL_ALPACA=${BASE_URL_ALPACA}
    depends_on:
      - redis

  redis:
    image: "redis/redis-stack"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--save 1 1

volumes:
  redis-data:

